GET http://localhost:3000/Person

###

GET http://localhost:3000/Person/5f21bf742c1f272822d83b03

###
GET http://localhost:3000/Person/5f76b045a1f0f33490c5662a

###

GET http://localhost:3000/Person/search/ania%20jo

###

POST http://localhost:3000/Person
Content-Type: application/json

{
  "name": "Jithin", 
  "nickName": "jith",
  "gender": "Male",
  "occupation": "Market Analyst",
  "company": "Infinite Solutions",    
  "address": "Bangalore"
}

###

DELETE  http://localhost:3000/Person/1